name: CI/CD Pipeline for ML Model

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        pytest tests/

    - name: Train model
      run: |
        python src/train.py

    - name: Archive model artifacts
      uses: actions/upload-artifact@v3
      with:
        name: trained-model
        path: |
          model/random_forest_model.joblib
          model/label_encoders.joblib
          model/feature_importance.png